/*
 * This file is generated by jOOQ.
*/
package com.example.provinceservice.domain.tables.records;


import com.example.provinceservice.domain.tables.ProvinceInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceInfoRecord extends UpdatableRecordImpl<ProvinceInfoRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -729936530;

    /**
     * Setter for <code>springclouddemo.province_info.province_id</code>.
     */
    public void setProvinceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>springclouddemo.province_info.province_id</code>.
     */
    public Integer getProvinceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>springclouddemo.province_info.province_name</code>.
     */
    public void setProvinceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>springclouddemo.province_info.province_name</code>.
     */
    public String getProvinceName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProvinceInfo.PROVINCE_INFO.PROVINCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProvinceInfo.PROVINCE_INFO.PROVINCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProvinceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProvinceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceInfoRecord value1(Integer value) {
        setProvinceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceInfoRecord value2(String value) {
        setProvinceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceInfoRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvinceInfoRecord
     */
    public ProvinceInfoRecord() {
        super(ProvinceInfo.PROVINCE_INFO);
    }

    /**
     * Create a detached, initialised ProvinceInfoRecord
     */
    public ProvinceInfoRecord(Integer provinceId, String provinceName) {
        super(ProvinceInfo.PROVINCE_INFO);

        set(0, provinceId);
        set(1, provinceName);
    }
}
