/*
 * This file is generated by jOOQ.
*/
package com.example.provinceservice.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceInfo implements Serializable {

    private static final long serialVersionUID = 1405968184;

    private Integer provinceId;
    private String  provinceName;

    public ProvinceInfo() {}

    public ProvinceInfo(ProvinceInfo value) {
        this.provinceId = value.provinceId;
        this.provinceName = value.provinceName;
    }

    public ProvinceInfo(
        Integer provinceId,
        String  provinceName
    ) {
        this.provinceId = provinceId;
        this.provinceName = provinceName;
    }

    public Integer getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProvinceInfo (");

        sb.append(provinceId);
        sb.append(", ").append(provinceName);

        sb.append(")");
        return sb.toString();
    }
}
