/*
 * This file is generated by jOOQ.
*/
package com.example.provinceservice.domain;


import com.example.provinceservice.domain.tables.CityInfo;
import com.example.provinceservice.domain.tables.ProvinceInfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Springclouddemo extends SchemaImpl {

    private static final long serialVersionUID = 1910895293;

    /**
     * The reference instance of <code>springclouddemo</code>
     */
    public static final Springclouddemo SPRINGCLOUDDEMO = new Springclouddemo();

    /**
     * The table <code>springclouddemo.city_info</code>.
     */
    public final CityInfo CITY_INFO = com.example.provinceservice.domain.tables.CityInfo.CITY_INFO;

    /**
     * The table <code>springclouddemo.province_info</code>.
     */
    public final ProvinceInfo PROVINCE_INFO = com.example.provinceservice.domain.tables.ProvinceInfo.PROVINCE_INFO;

    /**
     * No further instances allowed
     */
    private Springclouddemo() {
        super("springclouddemo", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CityInfo.CITY_INFO,
            ProvinceInfo.PROVINCE_INFO);
    }
}
