/*
 * This file is generated by jOOQ.
*/
package com.example.cityservice.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityInfo implements Serializable {

    private static final long serialVersionUID = 1236656026;

    private Integer cityId;
    private String  cityName;
    private Integer provinceId;

    public CityInfo() {}

    public CityInfo(CityInfo value) {
        this.cityId = value.cityId;
        this.cityName = value.cityName;
        this.provinceId = value.provinceId;
    }

    public CityInfo(
        Integer cityId,
        String  cityName,
        Integer provinceId
    ) {
        this.cityId = cityId;
        this.cityName = cityName;
        this.provinceId = provinceId;
    }

    public Integer getCityId() {
        return this.cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Integer getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CityInfo (");

        sb.append(cityId);
        sb.append(", ").append(cityName);
        sb.append(", ").append(provinceId);

        sb.append(")");
        return sb.toString();
    }
}
