/*
 * This file is generated by jOOQ.
*/
package com.example.cityservice.domain;


import com.example.cityservice.domain.tables.CityInfo;
import com.example.cityservice.domain.tables.ProvinceInfo;
import com.example.cityservice.domain.tables.records.CityInfoRecord;
import com.example.cityservice.domain.tables.records.ProvinceInfoRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>springclouddemo</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CityInfoRecord, Integer> IDENTITY_CITY_INFO = Identities0.IDENTITY_CITY_INFO;
    public static final Identity<ProvinceInfoRecord, Integer> IDENTITY_PROVINCE_INFO = Identities0.IDENTITY_PROVINCE_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CityInfoRecord> KEY_CITY_INFO_PRIMARY = UniqueKeys0.KEY_CITY_INFO_PRIMARY;
    public static final UniqueKey<ProvinceInfoRecord> KEY_PROVINCE_INFO_PRIMARY = UniqueKeys0.KEY_PROVINCE_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CityInfoRecord, Integer> IDENTITY_CITY_INFO = createIdentity(CityInfo.CITY_INFO, CityInfo.CITY_INFO.CITY_ID);
        public static Identity<ProvinceInfoRecord, Integer> IDENTITY_PROVINCE_INFO = createIdentity(ProvinceInfo.PROVINCE_INFO, ProvinceInfo.PROVINCE_INFO.PROVINCE_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CityInfoRecord> KEY_CITY_INFO_PRIMARY = createUniqueKey(CityInfo.CITY_INFO, "KEY_city_info_PRIMARY", CityInfo.CITY_INFO.CITY_ID);
        public static final UniqueKey<ProvinceInfoRecord> KEY_PROVINCE_INFO_PRIMARY = createUniqueKey(ProvinceInfo.PROVINCE_INFO, "KEY_province_info_PRIMARY", ProvinceInfo.PROVINCE_INFO.PROVINCE_ID);
    }
}
