/*
 * This file is generated by jOOQ.
*/
package com.example.cityservice.domain;


import com.example.cityservice.domain.tables.CityInfo;
import com.example.cityservice.domain.tables.ProvinceInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in springclouddemo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>springclouddemo.city_info</code>.
     */
    public static final CityInfo CITY_INFO = com.example.cityservice.domain.tables.CityInfo.CITY_INFO;

    /**
     * The table <code>springclouddemo.province_info</code>.
     */
    public static final ProvinceInfo PROVINCE_INFO = com.example.cityservice.domain.tables.ProvinceInfo.PROVINCE_INFO;
}
