/*
 * This file is generated by jOOQ.
*/
package com.example.cityservice.domain.tables;


import com.example.cityservice.domain.Keys;
import com.example.cityservice.domain.Springclouddemo;
import com.example.cityservice.domain.tables.records.CityInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityInfo extends TableImpl<CityInfoRecord> {

    private static final long serialVersionUID = 1818506166;

    /**
     * The reference instance of <code>springclouddemo.city_info</code>
     */
    public static final CityInfo CITY_INFO = new CityInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CityInfoRecord> getRecordType() {
        return CityInfoRecord.class;
    }

    /**
     * The column <code>springclouddemo.city_info.city_id</code>.
     */
    public final TableField<CityInfoRecord, Integer> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>springclouddemo.city_info.city_name</code>.
     */
    public final TableField<CityInfoRecord, String> CITY_NAME = createField("city_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>springclouddemo.city_info.province_id</code>.
     */
    public final TableField<CityInfoRecord, Integer> PROVINCE_ID = createField("province_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>springclouddemo.city_info</code> table reference
     */
    public CityInfo() {
        this("city_info", null);
    }

    /**
     * Create an aliased <code>springclouddemo.city_info</code> table reference
     */
    public CityInfo(String alias) {
        this(alias, CITY_INFO);
    }

    private CityInfo(String alias, Table<CityInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private CityInfo(String alias, Table<CityInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Springclouddemo.SPRINGCLOUDDEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CityInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CITY_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CityInfoRecord> getPrimaryKey() {
        return Keys.KEY_CITY_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CityInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<CityInfoRecord>>asList(Keys.KEY_CITY_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CityInfo as(String alias) {
        return new CityInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CityInfo rename(String name) {
        return new CityInfo(name, null);
    }
}
