/*
 * This file is generated by jOOQ.
*/
package com.example.cityservice.domain.tables;


import com.example.cityservice.domain.Keys;
import com.example.cityservice.domain.Springclouddemo;
import com.example.cityservice.domain.tables.records.ProvinceInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceInfo extends TableImpl<ProvinceInfoRecord> {

    private static final long serialVersionUID = -1575236253;

    /**
     * The reference instance of <code>springclouddemo.province_info</code>
     */
    public static final ProvinceInfo PROVINCE_INFO = new ProvinceInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProvinceInfoRecord> getRecordType() {
        return ProvinceInfoRecord.class;
    }

    /**
     * The column <code>springclouddemo.province_info.province_id</code>.
     */
    public final TableField<ProvinceInfoRecord, Integer> PROVINCE_ID = createField("province_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>springclouddemo.province_info.province_name</code>.
     */
    public final TableField<ProvinceInfoRecord, String> PROVINCE_NAME = createField("province_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>springclouddemo.province_info</code> table reference
     */
    public ProvinceInfo() {
        this("province_info", null);
    }

    /**
     * Create an aliased <code>springclouddemo.province_info</code> table reference
     */
    public ProvinceInfo(String alias) {
        this(alias, PROVINCE_INFO);
    }

    private ProvinceInfo(String alias, Table<ProvinceInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProvinceInfo(String alias, Table<ProvinceInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Springclouddemo.SPRINGCLOUDDEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProvinceInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PROVINCE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProvinceInfoRecord> getPrimaryKey() {
        return Keys.KEY_PROVINCE_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProvinceInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<ProvinceInfoRecord>>asList(Keys.KEY_PROVINCE_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinceInfo as(String alias) {
        return new ProvinceInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProvinceInfo rename(String name) {
        return new ProvinceInfo(name, null);
    }
}
